//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InscripcionesBrDbEntities : DbContext
    {
        public InscripcionesBrDbEntities()
            : base("name=InscripcionesBrDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adquirente> Adquirente { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Enajenante> Enajenante { get; set; }
        public virtual DbSet<Inscripcion> Inscripcion { get; set; }
        public virtual DbSet<Multipropietario> Multipropietario { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
    }
}
